import Foundation

enum Borough: String, Codable, CaseIterable, Sendable {
    case manhattan = "Manhattan"
    case brooklyn = "Brooklyn"
    case queens = "Queens"
    case bronx = "Bronx"
    case statenIsland = "Staten Island"
}

struct Neighborhood: Codable, Identifiable, Hashable, Sendable {
    let id: UUID
    let name: String
    let shortCode: String
    let borough: String

    enum CodingKeys: String, CodingKey {
        case id, name
        case shortCode = "short_code"
        case borough
    }

}

enum NeighborhoodDirectory {
    struct Entry {
        let name: String
        let shortCode: String
        let borough: String
    }

    static let all: [Entry] = [
        // Manhattan
        Entry(name: "Battery Park City", shortCode: "BPC", borough: "Manhattan"),
        Entry(name: "Central Park", shortCode: "C.PARK", borough: "Manhattan"),
        Entry(name: "Chelsea", shortCode: "CHELSEA", borough: "Manhattan"),
        Entry(name: "Chinatown", shortCode: "C-TOWN", borough: "Manhattan"),
        Entry(name: "Civic Center", shortCode: "CIVIC", borough: "Manhattan"),
        Entry(name: "East Harlem", shortCode: "E.HARLEM", borough: "Manhattan"),
        Entry(name: "East Village", shortCode: "EV", borough: "Manhattan"),
        Entry(name: "Ellis Island", shortCode: "EI", borough: "Manhattan"),
        Entry(name: "Financial District", shortCode: "FIDI", borough: "Manhattan"),
        Entry(name: "Flatiron District", shortCode: "FLATIRON", borough: "Manhattan"),
        Entry(name: "Governors Island", shortCode: "GI", borough: "Manhattan"),
        Entry(name: "Gramercy", shortCode: "GRAMERCY", borough: "Manhattan"),
        Entry(name: "Greenwich Village", shortCode: "GV", borough: "Manhattan"),
        Entry(name: "Hamilton Heights", shortCode: "HAM.HTS", borough: "Manhattan"),
        Entry(name: "Harlem", shortCode: "HARLEM", borough: "Manhattan"),
        Entry(name: "Hell's Kitchen", shortCode: "HK", borough: "Manhattan"),
        Entry(name: "Inwood", shortCode: "INWOOD", borough: "Manhattan"),
        Entry(name: "Kips Bay", shortCode: "KIPS", borough: "Manhattan"),
        Entry(name: "Liberty Island", shortCode: "LI", borough: "Manhattan"),
        Entry(name: "Little Italy", shortCode: "L.ITALY", borough: "Manhattan"),
        Entry(name: "Lower East Side", shortCode: "LES", borough: "Manhattan"),
        Entry(name: "Marble Hill", shortCode: "MARBLE", borough: "Manhattan"),
        Entry(name: "Midtown", shortCode: "MIDTOWN", borough: "Manhattan"),
        Entry(name: "Morningside Heights", shortCode: "MORNING", borough: "Manhattan"),
        Entry(name: "Murray Hill", shortCode: "MURRAY", borough: "Manhattan"),
        Entry(name: "NoHo", shortCode: "NOHO", borough: "Manhattan"),
        Entry(name: "Nolita", shortCode: "NOLITA", borough: "Manhattan"),
        Entry(name: "Randall's Island", shortCode: "RI", borough: "Manhattan"),
        Entry(name: "Roosevelt Island", shortCode: "ROOSVLT", borough: "Manhattan"),
        Entry(name: "SoHo", shortCode: "SOHO", borough: "Manhattan"),
        Entry(name: "Stuyvesant Town", shortCode: "STUY", borough: "Manhattan"),
        Entry(name: "Theater District", shortCode: "THEATER", borough: "Manhattan"),
        Entry(name: "Tribeca", shortCode: "TRIBECA", borough: "Manhattan"),
        Entry(name: "Two Bridges", shortCode: "TWO.BR", borough: "Manhattan"),
        Entry(name: "Upper East Side", shortCode: "UES", borough: "Manhattan"),
        Entry(name: "Upper West Side", shortCode: "UWS", borough: "Manhattan"),
        Entry(name: "Washington Heights", shortCode: "WASH.HTS", borough: "Manhattan"),
        Entry(name: "West Village", shortCode: "WV", borough: "Manhattan"),

        // Brooklyn
        Entry(name: "Bath Beach", shortCode: "BB", borough: "Brooklyn"),
        Entry(name: "Bay Ridge", shortCode: "BR", borough: "Brooklyn"),
        Entry(name: "Bedford-Stuyvesant", shortCode: "BS", borough: "Brooklyn"),
        Entry(name: "Bensonhurst", shortCode: "BENSONHURST", borough: "Brooklyn"),
        Entry(name: "Bergen Beach", shortCode: "BB", borough: "Brooklyn"),
        Entry(name: "Boerum Hill", shortCode: "BH", borough: "Brooklyn"),
        Entry(name: "Borough Park", shortCode: "BP", borough: "Brooklyn"),
        Entry(name: "Brighton Beach", shortCode: "BB", borough: "Brooklyn"),
        Entry(name: "Brooklyn Heights", shortCode: "BH", borough: "Brooklyn"),
        Entry(name: "Brownsville", shortCode: "BROWNSVILLE", borough: "Brooklyn"),
        Entry(name: "Bushwick", shortCode: "BUSHWICK", borough: "Brooklyn"),
        Entry(name: "Canarsie", shortCode: "CANARSIE", borough: "Brooklyn"),
        Entry(name: "Carroll Gardens", shortCode: "CARROLL", borough: "Brooklyn"),
        Entry(name: "Clinton Hill", shortCode: "CH", borough: "Brooklyn"),
        Entry(name: "Cobble Hill", shortCode: "COBBLE", borough: "Brooklyn"),
        Entry(name: "Columbia St", shortCode: "CS", borough: "Brooklyn"),
        Entry(name: "Coney Island", shortCode: "CI", borough: "Brooklyn"),
        Entry(name: "Crown Heights", shortCode: "CH", borough: "Brooklyn"),
        Entry(name: "Cypress Hills", shortCode: "CH", borough: "Brooklyn"),
        Entry(name: "DUMBO", shortCode: "DUMBO", borough: "Brooklyn"),
        Entry(name: "Downtown Brooklyn", shortCode: "DB", borough: "Brooklyn"),
        Entry(name: "Dyker Heights", shortCode: "DH", borough: "Brooklyn"),
        Entry(name: "East Flatbush", shortCode: "EF", borough: "Brooklyn"),
        Entry(name: "East New York", shortCode: "ENY", borough: "Brooklyn"),
        Entry(name: "East Williamsburg", shortCode: "E.WBURG", borough: "Brooklyn"),
        Entry(name: "Flatbush", shortCode: "FLATBUSH", borough: "Brooklyn"),
        Entry(name: "Flatlands", shortCode: "FLATLANDS", borough: "Brooklyn"),
        Entry(name: "Floyd Bennett Field", shortCode: "FBF", borough: "Brooklyn"),
        Entry(name: "Fort Greene", shortCode: "FG", borough: "Brooklyn"),
        Entry(name: "Fort Hamilton", shortCode: "FH", borough: "Brooklyn"),
        Entry(name: "Gerritsen Beach", shortCode: "GB", borough: "Brooklyn"),
        Entry(name: "Gowanus", shortCode: "GOWANUS", borough: "Brooklyn"),
        Entry(name: "Gravesend", shortCode: "GRAVESEND", borough: "Brooklyn"),
        Entry(name: "Green-Wood Cemetery", shortCode: "GWC", borough: "Brooklyn"),
        Entry(name: "Greenpoint", shortCode: "GPOINT", borough: "Brooklyn"),
        Entry(name: "Jamaica Bay", shortCode: "JB", borough: "Brooklyn"),
        Entry(name: "Kensington", shortCode: "KENSINGTON", borough: "Brooklyn"),
        Entry(name: "Manhattan Beach", shortCode: "MB", borough: "Brooklyn"),
        Entry(name: "Marine Park", shortCode: "MP", borough: "Brooklyn"),
        Entry(name: "Midwood", shortCode: "MIDWOOD", borough: "Brooklyn"),
        Entry(name: "Mill Basin", shortCode: "MB", borough: "Brooklyn"),
        Entry(name: "Navy Yard", shortCode: "NY", borough: "Brooklyn"),
        Entry(name: "Park Slope", shortCode: "SLOPE", borough: "Brooklyn"),
        Entry(name: "Plum Beach", shortCode: "PB", borough: "Brooklyn"),
        Entry(name: "Prospect Heights", shortCode: "PH", borough: "Brooklyn"),
        Entry(name: "Prospect Park", shortCode: "PP", borough: "Brooklyn"),
        Entry(name: "Prospect-Lefferts Gardens", shortCode: "PLG", borough: "Brooklyn"),
        Entry(name: "Red Hook", shortCode: "RED HOOK", borough: "Brooklyn"),
        Entry(name: "Sea Gate", shortCode: "SG", borough: "Brooklyn"),
        Entry(name: "Sheepshead Bay", shortCode: "SB", borough: "Brooklyn"),
        Entry(name: "South Slope", shortCode: "SS", borough: "Brooklyn"),
        Entry(name: "Sunset Park", shortCode: "SP", borough: "Brooklyn"),
        Entry(name: "Vinegar Hill", shortCode: "VH", borough: "Brooklyn"),
        Entry(name: "Williamsburg", shortCode: "WILLYB", borough: "Brooklyn"),
        Entry(name: "Windsor Terrace", shortCode: "WT", borough: "Brooklyn"),

        // Queens
        Entry(name: "Alley Pond Park", shortCode: "APP", borough: "Queens"),
        Entry(name: "Arverne", shortCode: "ARVERNE", borough: "Queens"),
        Entry(name: "Astoria", shortCode: "ASTORIA", borough: "Queens"),
        Entry(name: "Bay Terrace", shortCode: "BT", borough: "Queens"),
        Entry(name: "Bayside", shortCode: "BAYSIDE", borough: "Queens"),
        Entry(name: "Bayswater", shortCode: "BAYSWATER", borough: "Queens"),
        Entry(name: "Belle Harbor", shortCode: "BH", borough: "Queens"),
        Entry(name: "Bellerose", shortCode: "BELLEROSE", borough: "Queens"),
        Entry(name: "Breezy Point", shortCode: "BP", borough: "Queens"),
        Entry(name: "Briarwood", shortCode: "BRIARWOOD", borough: "Queens"),
        Entry(name: "Broad Channel", shortCode: "BC", borough: "Queens"),
        Entry(name: "Cambria Heights", shortCode: "CH", borough: "Queens"),
        Entry(name: "College Point", shortCode: "CP", borough: "Queens"),
        Entry(name: "Corona", shortCode: "CORONA", borough: "Queens"),
        Entry(name: "Cunningham Park", shortCode: "CP", borough: "Queens"),
        Entry(name: "Ditmars Steinway", shortCode: "DS", borough: "Queens"),
        Entry(name: "Douglaston", shortCode: "DOUGLASTON", borough: "Queens"),
        Entry(name: "East Elmhurst", shortCode: "EE", borough: "Queens"),
        Entry(name: "Edgemere", shortCode: "EDGEMERE", borough: "Queens"),
        Entry(name: "Elmhurst", shortCode: "ELMHURST", borough: "Queens"),
        Entry(name: "Far Rockaway", shortCode: "FR", borough: "Queens"),
        Entry(name: "Floral Park", shortCode: "FP", borough: "Queens"),
        Entry(name: "Flushing", shortCode: "FLUSHING", borough: "Queens"),
        Entry(name: "Flushing Meadows Corona Park", shortCode: "FMCP", borough: "Queens"),
        Entry(name: "Forest Hills", shortCode: "FH", borough: "Queens"),
        Entry(name: "Forest Park", shortCode: "FP", borough: "Queens"),
        Entry(name: "Fresh Meadows", shortCode: "FM", borough: "Queens"),
        Entry(name: "Glen Oaks", shortCode: "GO", borough: "Queens"),
        Entry(name: "Glendale", shortCode: "GLENDALE", borough: "Queens"),
        Entry(name: "Hollis", shortCode: "HOLLIS", borough: "Queens"),
        Entry(name: "Hollis Hills", shortCode: "HH", borough: "Queens"),
        Entry(name: "Holliswood", shortCode: "HOLLISWOOD", borough: "Queens"),
        Entry(name: "Howard Beach", shortCode: "HB", borough: "Queens"),
        Entry(name: "Jackson Heights", shortCode: "JH", borough: "Queens"),
        Entry(name: "Jamaica", shortCode: "JAMAICA", borough: "Queens"),
        Entry(name: "Jamaica Estates", shortCode: "JE", borough: "Queens"),
        Entry(name: "Jamaica Hills", shortCode: "JH", borough: "Queens"),
        Entry(name: "John F. Kennedy International Airport", shortCode: "JFKIA", borough: "Queens"),
        Entry(name: "Kew Gardens", shortCode: "KG", borough: "Queens"),
        Entry(name: "Kew Gardens Hills", shortCode: "KGH", borough: "Queens"),
        Entry(name: "LaGuardia Airport", shortCode: "LA", borough: "Queens"),
        Entry(name: "Laurelton", shortCode: "LAURELTON", borough: "Queens"),
        Entry(name: "Little Neck", shortCode: "LN", borough: "Queens"),
        Entry(name: "Long Island City", shortCode: "LIC", borough: "Queens"),
        Entry(name: "Maspeth", shortCode: "MASPETH", borough: "Queens"),
        Entry(name: "Middle Village", shortCode: "MV", borough: "Queens"),
        Entry(name: "Neponsit", shortCode: "NEPONSIT", borough: "Queens"),
        Entry(name: "Ozone Park", shortCode: "OP", borough: "Queens"),
        Entry(name: "Queens Village", shortCode: "QV", borough: "Queens"),
        Entry(name: "Rego Park", shortCode: "RP", borough: "Queens"),
        Entry(name: "Richmond Hill", shortCode: "RH", borough: "Queens"),
        Entry(name: "Ridgewood", shortCode: "RIDGEWOOD", borough: "Queens"),
        Entry(name: "Rockaway Beach", shortCode: "RB", borough: "Queens"),
        Entry(name: "Rockaway Park", shortCode: "RP", borough: "Queens"),
        Entry(name: "Rosedale", shortCode: "ROSEDALE", borough: "Queens"),
        Entry(name: "South Ozone Park", shortCode: "SOP", borough: "Queens"),
        Entry(name: "Springfield Gardens", shortCode: "SG", borough: "Queens"),
        Entry(name: "St. Albans", shortCode: "SA", borough: "Queens"),
        Entry(name: "Sunnyside", shortCode: "SUNNYSIDE", borough: "Queens"),
        Entry(name: "Whitestone", shortCode: "WHITESTONE", borough: "Queens"),
        Entry(name: "Woodhaven", shortCode: "WOODHAVEN", borough: "Queens"),
        Entry(name: "Woodside", shortCode: "WOODSIDE", borough: "Queens"),

        // Bronx
        Entry(name: "Allerton", shortCode: "ALLERTON", borough: "Bronx"),
        Entry(name: "Baychester", shortCode: "BAYCHESTER", borough: "Bronx"),
        Entry(name: "Belmont", shortCode: "BELMONT", borough: "Bronx"),
        Entry(name: "Bronx Park", shortCode: "BP", borough: "Bronx"),
        Entry(name: "Bronxdale", shortCode: "BRONXDALE", borough: "Bronx"),
        Entry(name: "Castle Hill", shortCode: "CH", borough: "Bronx"),
        Entry(name: "City Island", shortCode: "CI", borough: "Bronx"),
        Entry(name: "Claremont Village", shortCode: "CV", borough: "Bronx"),
        Entry(name: "Clason Point", shortCode: "CP", borough: "Bronx"),
        Entry(name: "Co-op City", shortCode: "COC", borough: "Bronx"),
        Entry(name: "Concourse", shortCode: "CONCOURSE", borough: "Bronx"),
        Entry(name: "Concourse Village", shortCode: "CV", borough: "Bronx"),
        Entry(name: "Country Club", shortCode: "CC", borough: "Bronx"),
        Entry(name: "Crotona Park", shortCode: "CP", borough: "Bronx"),
        Entry(name: "East Morrisania", shortCode: "EM", borough: "Bronx"),
        Entry(name: "Eastchester", shortCode: "EASTCHESTER", borough: "Bronx"),
        Entry(name: "Edenwald", shortCode: "EDENWALD", borough: "Bronx"),
        Entry(name: "Ferry Point Park", shortCode: "FPP", borough: "Bronx"),
        Entry(name: "Fieldston", shortCode: "FIELDSTON", borough: "Bronx"),
        Entry(name: "Fordham", shortCode: "FORDHAM", borough: "Bronx"),
        Entry(name: "Hart Island", shortCode: "HI", borough: "Bronx"),
        Entry(name: "Highbridge", shortCode: "HIGHBRIDGE", borough: "Bronx"),
        Entry(name: "Hunts Point", shortCode: "HP", borough: "Bronx"),
        Entry(name: "Kingsbridge", shortCode: "KINGSBRIDGE", borough: "Bronx"),
        Entry(name: "Longwood", shortCode: "LONGWOOD", borough: "Bronx"),
        Entry(name: "Melrose", shortCode: "MELROSE", borough: "Bronx"),
        Entry(name: "Morris Heights", shortCode: "MH", borough: "Bronx"),
        Entry(name: "Morris Park", shortCode: "MP", borough: "Bronx"),
        Entry(name: "Morrisania", shortCode: "MORRISANIA", borough: "Bronx"),
        Entry(name: "Mott Haven", shortCode: "MH", borough: "Bronx"),
        Entry(name: "Mount Eden", shortCode: "ME", borough: "Bronx"),
        Entry(name: "Mount Hope", shortCode: "MH", borough: "Bronx"),
        Entry(name: "North Brother Island", shortCode: "NBI", borough: "Bronx"),
        Entry(name: "North Riverdale", shortCode: "NR", borough: "Bronx"),
        Entry(name: "Norwood", shortCode: "NORWOOD", borough: "Bronx"),
        Entry(name: "Olinville", shortCode: "OLINVILLE", borough: "Bronx"),
        Entry(name: "Parkchester", shortCode: "PARKCHESTER", borough: "Bronx"),
        Entry(name: "Pelham Bay", shortCode: "PB", borough: "Bronx"),
        Entry(name: "Pelham Bay Park", shortCode: "PBP", borough: "Bronx"),
        Entry(name: "Pelham Gardens", shortCode: "PG", borough: "Bronx"),
        Entry(name: "Pelham Islands", shortCode: "PI", borough: "Bronx"),
        Entry(name: "Port Morris", shortCode: "PM", borough: "Bronx"),
        Entry(name: "Rikers Island", shortCode: "RI", borough: "Bronx"),
        Entry(name: "Riverdale", shortCode: "RIVERDALE", borough: "Bronx"),
        Entry(name: "Schuylerville", shortCode: "SCHUYLERVILLE", borough: "Bronx"),
        Entry(name: "Soundview", shortCode: "SOUNDVIEW", borough: "Bronx"),
        Entry(name: "Spuyten Duyvil", shortCode: "SD", borough: "Bronx"),
        Entry(name: "Throgs Neck", shortCode: "TN", borough: "Bronx"),
        Entry(name: "Tremont", shortCode: "TREMONT", borough: "Bronx"),
        Entry(name: "Unionport", shortCode: "UNIONPORT", borough: "Bronx"),
        Entry(name: "University Heights", shortCode: "UH", borough: "Bronx"),
        Entry(name: "Van Cortlandt Park", shortCode: "VCP", borough: "Bronx"),
        Entry(name: "Van Nest", shortCode: "VN", borough: "Bronx"),
        Entry(name: "Wakefield", shortCode: "WAKEFIELD", borough: "Bronx"),
        Entry(name: "West Farms", shortCode: "WF", borough: "Bronx"),
        Entry(name: "Westchester Square", shortCode: "WS", borough: "Bronx"),
        Entry(name: "Williamsbridge", shortCode: "WILLIAMSBRIDGE", borough: "Bronx"),
        Entry(name: "Woodlawn", shortCode: "WOODLAWN", borough: "Bronx"),

        // Staten Island
        Entry(name: "Arden Heights", shortCode: "AH", borough: "Staten Island"),
        Entry(name: "Arlington", shortCode: "ARLINGTON", borough: "Staten Island"),
        Entry(name: "Arrochar", shortCode: "ARROCHAR", borough: "Staten Island"),
        Entry(name: "Bay Terrace, Staten Island", shortCode: "BTSI", borough: "Staten Island"),
        Entry(name: "Bloomfield", shortCode: "BLOOMFIELD", borough: "Staten Island"),
        Entry(name: "Bull's Head", shortCode: "BH", borough: "Staten Island"),
        Entry(name: "Castleton Corners", shortCode: "CC", borough: "Staten Island"),
        Entry(name: "Charleston", shortCode: "CHARLESTON", borough: "Staten Island"),
        Entry(name: "Chelsea, Staten Island", shortCode: "CSI", borough: "Staten Island"),
        Entry(name: "Clifton", shortCode: "CLIFTON", borough: "Staten Island"),
        Entry(name: "Concord", shortCode: "CONCORD", borough: "Staten Island"),
        Entry(name: "Dongan Hills", shortCode: "DH", borough: "Staten Island"),
        Entry(name: "Eltingville", shortCode: "ELTINGVILLE", borough: "Staten Island"),
        Entry(name: "Emerson Hill", shortCode: "EH", borough: "Staten Island"),
        Entry(name: "Fort Wadsworth", shortCode: "FW", borough: "Staten Island"),
        Entry(name: "Freshkills Park", shortCode: "FP", borough: "Staten Island"),
        Entry(name: "Graniteville", shortCode: "GRANITEVILLE", borough: "Staten Island"),
        Entry(name: "Grant City", shortCode: "GC", borough: "Staten Island"),
        Entry(name: "Great Kills", shortCode: "GK", borough: "Staten Island"),
        Entry(name: "Great Kills Park", shortCode: "GKP", borough: "Staten Island"),
        Entry(name: "Grymes Hill", shortCode: "GH", borough: "Staten Island"),
        Entry(name: "Hoffman Island", shortCode: "HI", borough: "Staten Island"),
        Entry(name: "Howland Hook", shortCode: "HH", borough: "Staten Island"),
        Entry(name: "Huguenot", shortCode: "HUGUENOT", borough: "Staten Island"),
        Entry(name: "Latourette Park", shortCode: "LP", borough: "Staten Island"),
        Entry(name: "Lighthouse Hill", shortCode: "LH", borough: "Staten Island"),
        Entry(name: "Mariners Harbor", shortCode: "MH", borough: "Staten Island"),
        Entry(name: "Midland Beach", shortCode: "MB", borough: "Staten Island"),
        Entry(name: "New Brighton", shortCode: "NB", borough: "Staten Island"),
        Entry(name: "New Dorp", shortCode: "ND", borough: "Staten Island"),
        Entry(name: "New Dorp Beach", shortCode: "NDB", borough: "Staten Island"),
        Entry(name: "New Springville", shortCode: "NS", borough: "Staten Island"),
        Entry(name: "Oakwood", shortCode: "OAKWOOD", borough: "Staten Island"),
        Entry(name: "Park Hill", shortCode: "PH", borough: "Staten Island"),
        Entry(name: "Pleasant Plains", shortCode: "PP", borough: "Staten Island"),
        Entry(name: "Port Ivory", shortCode: "PI", borough: "Staten Island"),
        Entry(name: "Port Richmond", shortCode: "PR", borough: "Staten Island"),
        Entry(name: "Prince's Bay", shortCode: "PB", borough: "Staten Island"),
        Entry(name: "Randall Manor", shortCode: "RM", borough: "Staten Island"),
        Entry(name: "Richmondtown", shortCode: "RICHMONDTOWN", borough: "Staten Island"),
        Entry(name: "Rosebank", shortCode: "ROSEBANK", borough: "Staten Island"),
        Entry(name: "Rossville", shortCode: "ROSSVILLE", borough: "Staten Island"),
        Entry(name: "Shore Acres", shortCode: "SA", borough: "Staten Island"),
        Entry(name: "Silver Lake", shortCode: "SL", borough: "Staten Island"),
        Entry(name: "South Beach", shortCode: "SB", borough: "Staten Island"),
        Entry(name: "St. George", shortCode: "SG", borough: "Staten Island"),
        Entry(name: "Stapleton", shortCode: "STAPLETON", borough: "Staten Island"),
        Entry(name: "Todt Hill", shortCode: "TH", borough: "Staten Island"),
        Entry(name: "Tompkinsville", shortCode: "TOMPKINSVILLE", borough: "Staten Island"),
        Entry(name: "Tottenville", shortCode: "TOTTENVILLE", borough: "Staten Island"),
        Entry(name: "West Brighton", shortCode: "WB", borough: "Staten Island"),
        Entry(name: "Westerleigh", shortCode: "WESTERLEIGH", borough: "Staten Island"),
        Entry(name: "Willowbrook", shortCode: "WILLOWBROOK", borough: "Staten Island"),
        Entry(name: "Woodrow", shortCode: "WOODROW", borough: "Staten Island"),
    ]

    static func name(forShortCode code: String) -> String? {
        all.first { $0.shortCode == code }?.name
    }

    static func shortCode(forName name: String) -> String? {
        all.first { $0.name == name }?.shortCode
    }

    static func grouped() -> [(borough: String, entries: [Entry])] {
        let boroughs = ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]
        return boroughs.map { borough in
            (borough: borough, entries: all.filter { $0.borough == borough })
        }
    }
}
